name: Test

on:
 pull_request: {}
 push:
   branches: ["*"]
   tags: ["*"]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install .[github]

     - name: Test with tox
       run: tox
